### ISSUE TITLE
Change description

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [domenic/path-is-inside#3]
It is not very clear at first the difference between `is-path-inside` and `path-is-inside`. I would suggest to make it clear in the module description:

Tests whether one path is inside another path **including itself**.

**Comment by FagnerMartinsBrack** [comment]
X-Ref https://github.com/sindresorhus/is-path-inside/issues/3

**Comment by domenic** [comment]
I've never heard of that other module and don't really plan to change things about mine because another one exists...

**Comment by FagnerMartinsBrack** [comment]
This is just about creating a better ecosystem by making better abstractions and make it easy for folks to find the module they want. If two equally popular modules that appear in top Google results seems to have similar functionality, it is reasonable to ask that the difference between them can be spotted in the description.

I see no benefit in not doing it, does that makes sense?
